# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^infrastructure/.*\.yaml$
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict

  # Temporarily disable CloudFormation linting
  # - repo: https://github.com/aws-cloudformation/cfn-python-lint
  #   rev: v1.36.0
  #   hooks:
  #     - id: cfn-python-lint
  #       files: ^infrastructure/.*\.yaml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
